apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-k8s1-pb10-ultralight-org-persistent-1
  namespace: cms-admin
spec:
  capacity:
    storage: 10Gi
  volumeMode: Filesystem
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-persistent-1
  local:
    path: /data1
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - k8s1-pb10.ultralight.org
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-k8s1-pb10-ultralight-org-persistent-1
  namespace: cms-admin
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: local-persistent-1
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name:	pv-k8s1-pb10-ultralight-org-persistent-8
  namespace: cms-admin
spec:
  capacity:
    storage: 10Gi
  volumeMode: Filesystem
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-persistent-8
  local:
    path: /data8
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - k8s1-pb10.ultralight.org
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name:	pvc-k8s1-pb10-ultralight-org-persistent-8
  namespace: cms-admin
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: local-persistent-8
